import Head from "next/head";
import Image from "next/image";
import styles from "@component/styles/Home.module.css";
import { storefront } from "@component/utils/shopify";
import { useEffect, useRef, useState } from "react";

const gql = String.raw;

const productsQuery = gql`
  {
    products(first: 5) {
      edges {
        node {
          id
          title
          media(first: 5) {
            edges {
              node {
                ... on MediaImage {
                  id
                  image {
                    transformedSrc
                  }
                }
              }
            }
          }
        }
      }
    }
  }
`;

export default function Home({ products }: any) {
  const [barsWidth, setBarsWidth] = useState(10);
  const [bars, setBars] = useState(() => {
    const bars = [];
    for (let i = 0; i < 69; i++) {
      bars.push(1);
    }
    return bars;
  });
  useEffect(() => {
    console.log(window.innerHeight);
  }, []);
  console.log(products, bars);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <div
          style={{
            marginTop: 24,
            display: "flex",
          }}
        >
          <Image src={"/westadam.png"} width={180} height={360} alt="olswel" />
          <h1
            style={{
              fontSize: 48,
            }}
          >
            olswel.net
          </h1>
        </div>
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 10,
          }}
        >
          {products.map((product: any, i: any) => (
            <div
              style={{
                width: 240,
              }}
              key={i}
            >
              <h2
                style={{
                  wordWrap: "break-word",
                }}
              >
                {product.node.title}
              </h2>
              <Image
                src={product.node.media.edges[0].node.image.transformedSrc}
                alt={"product pic"}
                width={240}
                height={180}
              />
            </div>
          ))}
        </div>
        <div
          style={{
            display: "flex",
          }}
        >
          {bars.map((bar, i) => (
            <div
              key={i}
              className={styles.poop}
              style={{
                width: 20,
                position: "relative",
                marginTop: Math.random() * 100,
                border: "1px red solid",
                bottom: 0,
              }}
            />
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const data = await storefront(productsQuery);
  return {
    props: {
      products: data.data.products.edges,
    },
  };
}
