import Head from "next/head";
import styles from "@component/styles/Home.module.css";
import { storefront } from "@component/utils/shopify";

const gql = String.raw;

const productsQuery = gql`
  {
    products(first: 5) {
      edges {
        node {
          id
          title
        }
      }
    }
  }
`;

export default function Home({ products }) {
  console.log(products);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>olswel</h1>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const data = await storefront(productsQuery);
  return {
    props: {
      products: data,
    },
  };
}
