import Head from "next/head";
import Image from "next/image";
import styles from "@component/styles/Home.module.css";
import { storefront } from "@component/utils/shopify";
import { useEffect, useRef, useState } from "react";
import { useHover } from "react-aria";

const gql = String.raw;

const productsQuery = gql`
  {
    products(first: 5) {
      edges {
        node {
          id
          title
          media(first: 5) {
            edges {
              node {
                ... on MediaImage {
                  id
                  image {
                    transformedSrc
                  }
                }
              }
            }
          }
        }
      }
    }
  }
`;

function randomInteger(min: number, max: number) {
  return Math.floor(Math.random() * (max - min)) + min;
}

export default function Home({ products }: any) {
  const { hoverProps, isHovered } = useHover({});
  const [timestamp, setTimestamp] = useState(0);
  const [bars, setBars] = useState(() => {
    const bars = [];
    for (let i = 0; i < 130; i++) {
      bars.push(randomInteger(30, 60));
    }
    return bars;
  });
  const [smolBars, setSmolBars] = useState(() => {
    const bars = [];
    for (let i = 0; i < 130; i++) {
      bars.push(randomInteger(1, 30));
    }
    return bars;
  });

  useEffect(() => {
    console.log(window.innerHeight);
    // console.log(comments, "comments");
  }, []);
  console.log(products, bars);
  async function addAComment(e) {
    e.preventDefault();
    const data = {
      comment: e.target.comment.value,
      timestamp: Date.now(),
    };
    const jsonData = JSON.stringify(data);
    const endpoint = "/api/hello";
    const options = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: jsonData,
    };

    const response = await fetch(endpoint, options);

    // Get the response data from server as JSON.
    // If server returns the name submitted, that means the form works.
    const result = await response.json();
    console.log(result);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <div
          style={{
            marginTop: 24,
            display: "flex",
          }}
        >
          <Image
            src={"/olswellogo.png"}
            width={360}
            height={360}
            alt="olswel"
          />
          <h1
            style={{
              fontSize: 48,
            }}
          >
            olswel.net
          </h1>
        </div>
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 10,
          }}
        >
          {products.map((product: any, i: any) => (
            <div
              style={{
                width: 240,
              }}
              key={i}
            >
              <h2
                style={{
                  wordWrap: "break-word",
                }}
              >
                {product.node.title}
              </h2>
              <Image
                src={product.node.media.edges[0].node.image.transformedSrc}
                alt={"product pic"}
                width={240}
                height={180}
              />
            </div>
          ))}
        </div>
        <div
          style={{
            display: "flex",
            gap: 0.5,
          }}
          className={styles.pee}
        >
          {bars.map((bar, i) => (
            <div
              {...hoverProps}
              key={i}
              style={{
                width: 5,
                position: "relative",
                marginTop: bar,
                minHeight: 70,
                backgroundColor:
                  i < timestamp ? "orange" : isHovered ? "grey" : "darkgray",
                transition: "0.5s",
              }}
              onClick={() => {
                console.log(i);
                setTimestamp(() => i);
              }}
            />
          ))}
        </div>
        <div
          style={{
            display: "flex",
            gap: 0.5,
            marginTop: 1,
          }}
        >
          {smolBars.map((bar, i) => (
            <div
              key={i}
              className={styles.poop}
              style={{
                width: 5,
                position: "relative",
                height: bar,
              }}
            />
          ))}
        </div>
        <div
          style={{
            marginTop: 20,
          }}
        >
          <form
            className={styles.formForNewSpot}
            onSubmit={addAComment}
            method="post"
            encType="application/json"
          >
            <input
              type="text"
              placeholder="Leave a comment xD"
              id="comment"
              name="comment"
              style={{
                width: "48vw",
              }}
            />
            <button type="submit">Submit</button>
          </form>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const data = await storefront(productsQuery);
  return {
    props: {
      products: data.data.products.edges,
    },
  };
}
